language: node_js
node_js:
- 8
before_install:
- npm i -g firebase-tools
cache:
  directories:
  - node_modules
script:
- yarn run build
deploy:
  provider: firebase
  project: fir-travis-4b320
  skip_cleanup: true
  token:
    secure: Te5Zx/3ee1bMoOXg8vTjc1FuGDbJmUc0ATY5MxwOwEKYcMOAweHynlxy/OMDiqc6sOsl2Hac9A8cCQCFKF+kcUiRyKnpKIEb065A49VByLXK03s6fi+BX4w9f1aju4YwRFxr+E9ikaJrKnH6LQzOgpWe+z9zTn82Za9F+EDE8KbzKuJWhpci3sfQbEc2Vr5fgg8suMREnrwgQ71tRC8OjYTIanovywePp5egludIuaLLMOeGJHGDuiGkbo1F2dI5TwORUI8yb3akfbeZvHKEP9MT3uGkyrLiJVNNOQdnjLZ2X9MvXAdjrU2YSsgQWvPSd+AWnXdqmfLzGzhjIYeiQbridomB5aOwLNei6VgQka3eUeR3DJZtCXrJNJkGs43JvYiWQ2AO1D1ZP/7w9fOSUSL2Lh5m3mYfrp78a0u638X1JzAs6NDl0GkHi3Elz3cDqldye7TEP8xWw/W80s8H09hem+cQScmIGDzt1Hdi0KSU6KMfd73hAMUiPo2eWJ8eMAYNeZBcniltvtkwMBe/RbKJyiofhD5D2xf/DKAXPoW1MQZptD74YFswZQV2cTpZDZdZMa5KO3/hQzaG556ARVrLPpV+gmYLkO6acMlNtiVLp75tqzNErbTmFpOwpUqlUy4g6p4TlJFO95D1p1vfCNqMvKndlOIAKS8ug+L1dds=
